[package]
name        = "museum-giftshop"
description = "test"
version     = "1.0.0"
flix        = "0.34.0"
authors     = ["John Doe <john@example.com>"]

[dependencies]
"github:flix/museum-clerk" = "1.0.0"
